#!/bin/bash

if [ $1 -eq 1 ]; then
    export FILEPATH=src/data/car/master.dat
    ant server -Dport=4000
fi

if [ $1 -eq 2 ]; then
    export FILEPATH=src/data/flight/master.dat
    ant server -Dport=4001
fi

if [ $1 -eq 3 ]; then
    export FILEPATH=src/data/room/master.dat
    ant server -Dport=4002
fi
